# Generated by Django 3.0.5 on 2020-05-06 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0004_auto_20200430_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=20, verbose_name='测试用例名称')),
                ('test_type', models.IntegerField(default=0, verbose_name='用例类型')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.UserInfo')),
            ],
            options={
                'verbose_name_plural': '测试用例',
                'db_table': 'test_case',
            },
        ),
    ]
