# Generated by Django 3.0.5 on 2020-05-13 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_userinfo_is_delete'),
        ('test_case', '0003_testcase_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.UserInfo'),
        ),
        migrations.CreateModel(
            name='TestCaseRunnerDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=100, verbose_name='测试地址')),
                ('browser', models.CharField(max_length=10, verbose_name='浏览器')),
                ('Version', models.CharField(max_length=10, verbose_name='版本')),
                ('report_address', models.CharField(max_length=10, verbose_name='测试用例地址')),
                ('loop', models.IntegerField(default=1, verbose_name='循环次数')),
                ('importAddress', models.CharField(max_length=100, verbose_name='测试报告地址')),
                ('moudle', models.DateTimeField(default='全部', max_length=15, verbose_name='运行的模块')),
                ('runner_time', models.DateTimeField(auto_now_add=True, verbose_name='运行时间')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_case.TestCase')),
            ],
            options={
                'verbose_name_plural': '测试用例运行详情',
                'db_table': 'testcase_runner_detail',
            },
        ),
    ]
