# Generated by Django 3.0.5 on 2020-05-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_case', '0004_auto_20200513_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaserunnerdetail',
            name='Version',
            field=models.CharField(default='', max_length=10, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='testcaserunnerdetail',
            name='moudle',
            field=models.CharField(default='全部', max_length=15, verbose_name='运行的模块'),
        ),
        migrations.AlterField(
            model_name='testcaserunnerdetail',
            name='report_address',
            field=models.CharField(max_length=100, verbose_name='测试用例地址'),
        ),
    ]
