# Generated by Django 3.0.5 on 2020-12-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_case', '0005_auto_20200513_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcaserunnerdetail',
            old_name='moudle',
            new_name='moudles',
        ),
    ]
