IP: zs-beta.cntracechain.com/#/login
Browser: FireFox
ReportAddress: D:\AutoTest\report\
loop: 1
ImportAddress: "D:\\AutoTest\\exceltemplate\\\u6D4B\u8BD5.xlsx"
Moudle: "\u5168\u90E8"
Version: '76'
CaseNum: 1
