IP: zs-beta.cntracechain.com/#/login
Browser: Google Chrome
ReportAddress: D:\AutoTest\report\
loop: 1
ImportAddress: "D:\\AutoTest\\exceltemplate\\\u6D4B\u8BD5\u7528\u4F8B.xlsx"
Moudle: "\u5168\u90E8"
Version: '86'
CaseNum: 2
