# Generated by Django 3.0.5 on 2020-04-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=20, verbose_name='联系方式')),
                ('email', models.CharField(max_length=20, verbose_name='邮箱')),
                ('sex', models.CharField(default=0, max_length=1, verbose_name='性别')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
