# Generated by Django 3.0.5 on 2020-04-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='sex',
            field=models.IntegerField(default=0, max_length=1, verbose_name='性别'),
        ),
    ]
