# Generated by Django 3.0.5 on 2020-04-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20200429_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=20, verbose_name='联系方式')),
                ('email', models.CharField(max_length=20, verbose_name='邮箱')),
                ('sex', models.IntegerField(default=0, verbose_name='性别')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.DeleteModel(
            name='user_info',
        ),
    ]
