# Generated by Django 3.0.5 on 2020-04-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20200430_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='userinfo',
            unique_together={('mobile',)},
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='user',
        ),
    ]
