# Generated by Django 3.0.5 on 2020-05-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20200430_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_delete',
            field=models.IntegerField(default=0, verbose_name='是否删除'),
        ),
    ]
