# Generated by Django 3.0.5 on 2020-12-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_userinfo_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default='123456', max_length=20, verbose_name='密码'),
        ),
    ]
